In [ ]:
import numpy as np

matrix = np.ones((500, 500))

padded_matrix = np.zeros((508, 508))

for i in range(500):
    for j in range(500):
        padded_matrix[i+4, j+4] = matrix[i, j]
print(padded_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [34]:
def swap_diagonal_with_center_row(mat):
    n = len(mat)
    mid = n // 2

    for i in range(n):
        temp = mat[i][i]
        mat[i][i] = mat[mid][i]
        mat[mid][i] = temp
    return mat  
test_matrix = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

result = swap_diagonal_with_center_row(test_matrix.copy())
print("Transformed Matrix:", result)

Transformed Matrix: [[11  2  3  4  5]
 [ 6 12  8  9 10]
 [ 1  7 13 19 25]
 [16 17 18 14 20]
 [21 22 23 24 15]]


In [42]:
import torch

vector1 = torch.tensor([1.0, 2.0, 3.0])
vector2 = torch.tensor([4.0, 5.0, 6.0])

dot_product = torch.dot(vector1, vector2)
cross_product = torch.cross(vector1, vector2)
print("Dot Product:", dot_product)
print("Cross Product:", cross_product)


Dot Product: tensor(32.)
Cross Product: tensor([-3.,  6., -3.])


In [37]:
import torch

gpu_available = torch.cuda.is_available()
print("GPU Available:", gpu_available)

if ~gpu_available:
    print("No GPU available. Using CPU.")

GPU Available: False
No GPU available. Using CPU.


C:\Users\Hashir\AppData\Local\Temp\ipykernel_18724\1638244605.py:6: DeprecationWarning: Bitwise inversion '~' on bool is deprecated and will be removed in Python 3.16. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
  if ~gpu_available:


In [ ]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

A = torch.tensor([[1., 2.],[3., 4.]])
B = torch.tensor([[5., 6.],[7., 8.]])

A = A.to(device)
B = B.to(device)

C = torch.matmul(A, B)

print(C)


tensor([[19., 22.],
        [43., 50.]])


In [ ]:
import torch

X = torch.tensor([[1., 2., 3.],[4., 5., 6.]])

X_min = X.min()
X_max = X.max()

print((X - X_min) / (X_max - X_min))

tensor([[0.0000, 0.2000, 0.4000],
        [0.6000, 0.8000, 1.0000]])


In [3]:
import torch

x = torch.tensor(2.0, requires_grad=True)
y = x**2 + 3*x + 5

y.backward()

print(x.grad)


tensor(7.)
