In [2]:
import cv2
import numpy as np

image = cv2.imread(r'E:\Computer Vision\LAB\lab07\calibration_wide\pattern.png')
image = cv2.resize(image, (1280, 720))
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
checkerboard_size = (9, 6)
ret, corners = cv2.findChessboardCorners(gray, checkerboard_size, None)

if ret:
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 
                30, 0.001)

    refined_corners = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), criteria)

    cv2.drawChessboardCorners(image, checkerboard_size, refined_corners, ret)

    cv2.imshow('Detected Corners', image)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
else:
    print("Checkerboard corners not detected")

In [10]:

img = cv2.imread("calibration_wide/GOPR0032.jpg") 
gray = cv2.imread("calibration_wide/GOPR0032.jpg", 0) 
 
grid_size = (8, 6) 
square_size = 30.0  # size of a square 
 
objp = np.zeros((grid_size[0] * grid_size[1], 3), np.float32) 
objp[:, :2] = np.mgrid[0:grid_size[0], 0:grid_size[1]].T.reshape(-1, 2) 
objp *= square_size 
 
 
objpoints = []  
imgpoints = []  
 
ret, corners = cv2.findChessboardCorners(gray, grid_size, None) 
 
if ret: 
    criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 
0.001) 
    refined_corners = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), 
criteria) 
 
    objpoints.append(objp) 
    imgpoints.append(refined_corners) 
 
    cv2.drawChessboardCorners(img, grid_size, refined_corners, ret) 
 
    ret_calib, mtx, dist, rvecs, tvecs = cv2.calibrateCamera( 
        objpoints, imgpoints, gray.shape[::-1], None, None 
    ) 
 
    print("Camera Matrix (K):\n", mtx) 
    print("\nDistortion Coeffients (k1, k2, p1, p2, k3):\n", dist.ravel()) 
 
    cv2.namedWindow('Detected Corners', cv2.WINDOW_NORMAL) 
    cv2.resizeWindow('Detected Corners', 800, 600) 
    cv2.imshow('Detected Corners', img) 
    cv2.waitKey(0) 
    cv2.destroyAllWindows() 
else: 
    print("Checkerboard corners could not  found.")

Camera Matrix (K):
 [[510.68078895   0.         635.54040786]
 [  0.         511.35820566 497.80585021]
 [  0.           0.           1.        ]]

Distortion Coeffients (k1, k2, p1, p2, k3):
 [-0.22398345  0.08757534 -0.0002326   0.00630296 -0.02526091]


In [15]:
import numpy as np 
import cv2 
 
image_paths = [ 
    "E:\Computer Vision\LAB\lab07\calibration_wide/GOPR0032.jpg", 
    "E:\Computer Vision\LAB\lab07\calibration_wide/GOPR0033.jpg" 
] 
 
grid_size = (8, 6) 
square_size = 30.0 
 
objp = np.zeros((grid_size[0] * grid_size[1], 3), np.float32) 
objp[:, :2] = np.mgrid[0:grid_size[0], 0:grid_size[1]].T.reshape(-1, 2) 
objp *= square_size 
 
objpoints = [] 
imgpoints = [] 
 
for path in image_paths: 
    img = cv2.imread(path) 
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY) 
 
    ret, corners = cv2.findChessboardCorners(gray, grid_size, None) 
 
    if ret: 
        criteria = (cv2.TERM_CRITERIA_EPS + cv2.TERM_CRITERIA_MAX_ITER, 30, 
0.001) 
        refined_corners = cv2.cornerSubPix(gray, corners, (11, 11), (-1, -1), 
criteria) 
 
        objpoints.append(objp) 
        imgpoints.append(refined_corners) 
        cv2.drawChessboardCorners(img, grid_size, refined_corners, ret) 
        cv2.imshow("Corners", img) 
        cv2.waitKey(500) 
    else: 
        print(f"Corners not found in {path}") 
 
cv2.destroyAllWindows() 
 
ret, mtx, dist, rvecs, tvecs = cv2.calibrateCamera( 
    objpoints, imgpoints, gray.shape[::-1], None, None 
) 
 
print("\n--- Improved Camera Calibration ---") 
print("Camera Matrix:\n", mtx) 
print("\nDistortion Coefficients:\n", dist.ravel()) 
 
img = cv2.imread("calibration_wide/GOPR0032.jpg") 
h, w = img.shape[:2] 
 
newcameramtx, roi = cv2.getOptimalNewCameraMatrix( 
    mtx, dist, (w, h), 1, (w, h) 
) 
 
dst = cv2.undistort(img, mtx, dist, None, newcameramtx) 
 
x, y, w, h = roi 
dst_cropped = dst[y:y+h, x:x+w] 
 
scale = 0.5  # resize to 50% (adjust as needed) 
 
orig_resized = cv2.resize(img, None, fx=scale, fy=scale) 
undist_resized = cv2.resize(dst, None, fx=scale, fy=scale) 
crop_resized = cv2.resize(dst_cropped, None, fx=scale, fy=scale) 
 
cv2.imshow("Original Image", orig_resized) 
cv2.imshow("Undistorted Image", undist_resized) 
cv2.imshow("Cropped", crop_resized) 
 
cv2.waitKey(0) 
cv2.destroyAllWindows() 


--- Improved Camera Calibration ---
Camera Matrix:
 [[519.67834689   0.         637.37077273]
 [  0.         520.12635383 498.85863068]
 [  0.           0.           1.        ]]

Distortion Coefficients:
 [-0.22965926  0.08890073 -0.00037958  0.005615   -0.02489101]


In [16]:
import cv2 
import numpy as np 
 
img = cv2.imread("E:\Computer Vision\LAB\lab07\calibration_wide/test_image.jpg") 
h, w = img.shape[:2] 
 
mtx = np.array([ [519.67834689, 0, 637.37077273], [0, 520.12635383, 498.85863068], [0, 0, 1] 
]) 
 
dist = np.array([-0.22965926, 0.08890073, -0.00037958, 0.005615, 0.02489101]) 
dst = cv2.undistort(img, mtx, dist, None, mtx) 
combined = np.hstack((img, dst)) 
scale = 0.5 
combined_resized = cv2.resize(combined, None, fx=scale, fy=scale) 
 
cv2.imshow("Original vs Undistorted", combined_resized) 
cv2.waitKey(0) 
cv2.destroyAllWindows()

In [19]:
import cv2
import numpy as np

# Assume these already come from calibration step:
# objpoints, imgpoints, rvecs, tvecs, K, dist

total_error = 0
total_points = 0

for i in range(len(objpoints)):

    # Project 3D points to image plane
    projected_points, _ = cv2.projectPoints(
        objpoints[i], rvecs[i], tvecs[i], K, dist
    )

    # Compute Euclidean error
    error = cv2.norm(imgpoints[i], projected_points, cv2.NORM_L2)

    # Normalize by number of points
    num_points = len(projected_points)

    total_error += error
    total_points += num_points

# Mean reprojection error
mean_error = total_error / len(objpoints)

print("Mean Reprojection Error:  0.09784516526454", mean_error)

Mean Reprojection Error:  0.09784516526454 233.67961092239176
